image: node
before_script:
  - npm i markdown-spellcheck -g --silent
cache:
  paths:
    - /usr/local/lib/node_modules
    - /usr/local/bin
    - ~/diatex
variables:
  DIATEX_CDN_REPO: benjamincaldwell/gitcdn
  DIATEX_IMAGE_BASE_PATH: "http://gitcdn.bcaldwell.ca"
  DIATEX_URL: "https://diatex.bcaldwell.ca"

spell_check:
  before_script:
    - npm i markdown-spellcheck -g --silent
  script:
    - mdspell --en-us -n -r -a "**/*.md" "!**/jekyll/**/*.md"
  only:
    - master
  allow_failure: true

gh_pages:
  image: ruby:2.4
  before_script:
    - export LC_ALL=C.UTF-8
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US.UTF-8
    
    - gem install htmlbeautifier
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "${GITLAB_CI_WRITE_KEY}")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo "${SSH_SERVER_HOSTKEYS}" > ~/.ssh/known_hosts'
    - '[ -d "~/diatex" ] && cd ~/diatex && git reset --hard origin/master'
    - '[ ! -d "~/diatex" ] && git clone https://github.com/benjamincaldwell/diatex.git ~/diatex'

  script:
    - git fetch
    - git config --global user.email "bot@bcaldwell.ca" && git config --global user.name "Benjamin Bot"

    # Run diatex
#    - ruby ~/diatex/diatex .
#    - git status
#    - git add --all .
#    - git commit -m "Convert latex and diagram for '$(git log -1 --pretty=%B)' [ci skip]" || true
#    - git push origin master || true

    # Publish the Github Pages Site
    - mv jekyll/* .
    - rm -rf jekyll
    - ruby ./bin/toc.rb
    - ruby ./bin/format_page.rb
    - git status
    - git add --all .
    - git commit -m 'Build jekyll site'
    - git remote add gitlab git@gitlab.caldwellbenjam.in:benjamin/continuous-learning.git || true
    - git push gitlab HEAD:gh-pages -f
  only:
    - master
  environment:
    name: github pages
    url: https://cl.bcaldwell.ca
