image: node
before_script:
  - npm i markdown-spellcheck -g --silent
cache:
  paths:
  - /usr/local/lib/node_modules
  - /usr/local/bin

spell_check:
  before_script:
    - npm i markdown-spellcheck -g --silent
  script:
    - mdspell --en-us -n -r -a "**/*.md" "!**/jekyll/**/*.md"
  only:
    - master
    
gh_paages:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install htmlbeautifier
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITLAB-CI-WRITE-KEY")
  script:
    - git fetch
    - git config --global user.email "bot@bcaldwell.ca" && git config --global user.name "Benjamin Bot"

    # Publish the Github Pages Site
    - mv jekyll/* .
    - rm -rf jekyll
    - ruby ./bin/toc.rb
    - ruby ./bin/format_page.rb
    - git status
    - git add --all .
    - git commit -m 'Build jekyll site'
    - git push gitlab HEAD:gh-pages -f
  only:
    - master